language: node_js
node_js:
  - "0.10"
services:
  - mongodb
before_script:
  - "export CHROME_BIN=chromium-browser"
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - npm install -g casperjs gulp
notifications:
  slack: startersacademy-01:wDXRSBJAGrPfu5YLzZt4i6dW
